# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0ea527812c540bfbe1fa301c790a41d5bc68a354b745717e3f4e696a6ce49dc52db9c21ddd605b8e4eeb4189ab1a07162479217b474e4435ef4d4aa9968022c

test:
  secret_key_base: 34702eebf1da2f40635ac01e51fbe61c332147d1bf78f6999c10a37fc1867a1520f429fa23b94310205ee4344045624c99bd34c86d9b6c3e10946033324f2e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
